Signup Api end point in UserController with corresponding Business lo…
cushivas/Trello_quora pull request #3
Opened 2021-02-06 05:59 UTC by soniyakocher

…gic is implemented

2021-02-06 15:57 UTC, cushivas requested changes
Comments Inline

2021-02-06 15:57 UTC, cushivas commented on quora-db/src/main/resources/sql/quora.sql
> +
This line can be removed

2021-02-06 15:57 UTC, cushivas commented on quora-service/src/main/java/com/upgrad/quora/service/Entity/UserEntity.java
> +    @Column(name="PASSWORD")
Please use @ToStringExclude for password & salt field

2021-02-06 15:57 UTC, cushivas commented on quora-service/src/main/java/com/upgrad/quora/service/business/UserBusinessService.java
> +        UserEntity userEntity1= userDao.getUserByUsername(userEntity.getUsername());
rather than naming it userEntity1, can you use more meaningful name ? Like existingUserEntity ?
You can use the same object in place of userEntity2

2021-02-06 15:57 UTC, cushivas commented on quora-service/src/main/java/com/upgrad/quora/service/dao/UserDao.java
> +        } catch (NoResultException nre) {
nre variable is currently not used, for now we can add  System.Out.println (nre.message)

2021-02-07 05:04 UTC, swapdutt reviewed
Looks good to me

2021-02-07 05:07 UTC, swapdutt reviewed
User Business Service Class:
1. Please use different variable name for checking the user entity object.
2. Use try-catch-finally block for checking password is null or not.

2021-02-07 05:08 UTC, swapdutt commented on quora-service/src/main/java/com/upgrad/quora/service/business/UserBusinessService.java
> +        UserEntity userEntity1= userDao.getUserByUsername(userEntity.getUsername());
There is a chance of getting the variable over-written so using of two different variables will resolve it easily with faster execution

2021-02-07 05:42 UTC, swapdutt reviewed
Please put in the else block where we are checking the password is null and then return the variable userEntity at last
String[] encryptedText = PasswordCryptographyProvider.encrypt(userEntity.getPassword());
userEntity.setSalt(encryptedText[0]);
userEntity.setPassword(encryptedText[1]);

2021-02-07 06:00 UTC, cushivas approved these changes
Looks Good

2021-02-07 14:40 UTC, swapdutt approved these changes
Good to go

2021-02-07 14:41 UTC, merged